BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT COUNT(*) FROM site_county;
INSERT INTO site_county VALUES (12345, 10);
SELECT COUNT(*) FROM site_county;
COMMIT;

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
INSERT INTO site_county VALUES (12345, 11);
SELECT COUNT(*) FROM site_county WHERE site_id = 12345;
COMMIT;